
sa_museum_homepage:
    path:     /
    defaults:
        _controller: SAMuseumBundle:Default:index

sa_museum_view:
    path:     /booking/{id}
    defaults:
        _controller: SAMuseumBundle:Booking:view

sa_museum_add:
    path:     /add
    defaults:
        _controller: SAMuseumBundle:Booking:add

sa_museum_infos:
    path:     /infos
    defaults:
        _controller: SAMuseumBundle:Default:infos

museum_tickets_checkout:
    path:     /checkout/{id}
    defaults:
        _controller: SAMuseumBundle:Order:checkout

museum_tickets_order:
    path:     /prepare/{id}
    defaults:
        _controller: SAMuseumBundle:Order:prepare

museum_payments_confirm:
    path:    /confirm/{id}
    defaults:
        _controller: SAMuseumBundle:Order:confirm

museum_tickets:
    path:    /tickets/{bookedday}
    defaults:
        _controller: SAMuseumBundle:Ticket:view

museum_mailsend:
    path:     /book_confirmed/{id}
    defaults:
        _controller: SAMuseumBundle:Booking:mail

museum_test:
    path:    /test
    defaults:
        _controller: SAMuseumBundle:Booking:test

museum_ln:
    path:    /Mentions Legales
    defaults:
        _controller: SAMuseumBundle:Default:legalNotice

