

sa_museum_homepage:
    path:     /
    defaults:
        _controller: SAMuseumBundle:Default:index

sa_museum_view:
    path:     /booking/{id}
    defaults:
        _controller: SAMuseumBundle:Booking:view


sa_museum_add:
    path:     /add
    defaults:
        _controller: SAMuseumBundle:Booking:add


sa_museum_infos:
    path:     /infos
    defaults:
        _controller: SAMuseumBundle:Default:infos

