

sa_museum_homepage:
    path:     /{page}
    defaults:
        _controller: SAMuseumBundle:Default:index
        page:        1
    requirements:
        page: \d*

sa_museum_view:
    path:     /booking/{id}
    defaults:
        _controllet: SAMuseumBundle:Booking:view
    requirements:
      id: \d+

sa_museum_add:
    path:     /add
    defaults:
        _controller: SAMuseumBundle:Booking:add


sa_museum_infos:
    path:     /infos
    defaults:
        _controller: SAMuseumBundle:Default:infos

