services:
#    sa_museum.example:
#        class: SA\MuseumBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
     sa_museum.limit:
         class: SA\MuseumBundle\Limit\SALimit

     sa_museum.bday:
         class: SA\MuseumBundle\Birthday\SABday

     sa_museum.charge:
         class: SA\MuseumBundle\Price\SACharge

     sa_museum.bookingservice:
         class: SA\MuseumBundle\Services\BookingManager
         arguments: ["@doctrine.orm.entity_manager"]